### PR TITLE
Use KRaft (Kafka without Zookeeper)

### PR DESCRIPTION
**Pull request by whithajess**
This is a suggestion to change the docker image used in this example repo.

- Uses Kafka itself for the Quorum Controller
  - see: https://developer.confluent.io/learn/kraft/
- Switch to the much more up to date Bitnami Kafka Image
  - up to Kafka 3.1 (wurstmeister is still on 2.8)

Should work exactly as it did with less overhead on the machine running it!

More details around `KRaft` and why in my PR over on the image repo: https://github.com/bitnami/bitnami-docker-kafka/pull/235

### CODE REVIEW

**Comment by mensfeld** [comment]
@whithajess would you mind applying the same for karafka 2.0 and waterdrop? :pray:

**Comment by whithajess** [comment]
@mensfeld Just holding off this briefly while I wait for my full set of changes to go into the image repo: https://github.com/bitnami/bitnami-docker-kafka/pull/235

**Comment by mensfeld** [comment]
@whithajess sure no problem :) take your time

**Comment by whithajess** [comment]
> @mensfeld Just holding off this briefly while I wait for my full set of changes to go into the image repo: [bitnami/bitnami-docker-kafka#235](https://github.com/bitnami/bitnami-docker-kafka/pull/235)

This is now merged so I have updated this PR to match.

> @whithajess would you mind applying the same for karafka 2.0 and waterdrop? 🙏

Have followed this through: https://github.com/karafka/karafka/pull/836 and https://github.com/karafka/waterdrop/pull/241 with the caveats listed in the _descriptions_ around `KAFKA_CREATE_TOPICS` if its required I can make those changes also.

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
Merged. Thank you. Let me look into the rest.

**Pull request merged**
