### PR TITLE
Error: no pause after the error when custom topic mapper defined

### PR DESCRIPTION
**Pull request by Michanio**
When custom topic mapper is defined there is no pause time after the error.
Error retry is called every second.
As I can see there is wrong output of the `outgoing` mapper method that duplicates the prefix at the beginning: 
`sample-prefix.sample-prefix.error_test`

```
[example_app_error_example] {sample-prefix.error_test: 0}: Fetcher thread exited.
I, [2022-03-21T07:19:32.089928 #90028]  INFO -- : [[example_app_error_example] {}:] Leaving group `example_app_error_example`
I, [2022-03-21T07:19:32.104490 #90028]  INFO -- : [[example_app_error_example] {}:] Disconnecting broker 1001
E, [2022-03-21T07:19:32.105040 #90028] ERROR -- : Client fetch loop error: Ups something went wrong
I, [2022-03-21T07:19:32.105224 #90028]  INFO -- : Outgoing: sample-prefix.sample-prefix.error_test
I, [2022-03-21T07:19:32.105679 #90028]  INFO -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] Joining group `example_app_error_example`
I, [2022-03-21T07:19:32.105877 #90028]  INFO -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] There are no partitions to fetch from, sleeping for 1s
E, [2022-03-21T07:19:32.114519 #90028] ERROR -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] Failed to join group; resetting member id and retrying in 1s...
I, [2022-03-21T07:19:33.111719 #90028]  INFO -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] There are no partitions to fetch from, sleeping for 1s
I, [2022-03-21T07:19:33.119731 #90028]  INFO -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] Joining group `example_app_error_example`
I, [2022-03-21T07:19:33.138200 #90028]  INFO -- : [[example_app_error_example] {sample-prefix.error_test: 0}:] Joined group `example_app_error_example` with member id `example_app-4f7229c3-c646-441a-95de-307185b8c2de`
```

### CODE REVIEW

**Comment by mensfeld** [comment]
@Michanio this example does not work. WaterDrop does not uses topic mappers. Topic mappers are part of responders, thus dispatched messages are never consumed as consuming is on a different topic than sending

**Comment by mensfeld** [comment]
ok I was able to reproduce

**Comment by Michanio** [comment]
Great.
We fixed it by adding the prefix ( in `outgoing` meyhod) only if it's not already prefixed. It works but there is still a bug.

**Comment by mensfeld** [comment]
Hey,

Took me a while to figure out. Won't fix thus closing. I'm close to releasing 2.0 and concept of topic matters was removed.

It was never a good idea and does not work with concurrent async world.

**Pull request closed without merging**
